# Create a render.yaml file in your project root
services:
  - type: web
    name: markdown-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
